Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *  #Importē skaitlisko metožu funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *  #Importē skaitlisko metožu funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 1, in <module>
    from numpy import *  #Importē skaitlisko metožu funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 3, in <module>
    from numpy import *  #Importē skaitlisko metožu funkcijas
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> sds
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    sds
NameError: name 'sds' is not defined
>>> 
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> 5
5
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B1.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> 
===================== RESTART: /home/user/RTR105/1B1.py =====================

Warning (from warnings module):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py", line 281
    'Matplotlib is building the font cache using fc-list. '
UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.

===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================

===================== RESTART: /home/user/RTR105/1B1.py =====================
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================
Traceback (most recent call last):
  File "/home/user/RTR105/1B2.py", line 7, in <module>
    y1 = x
NameError: name 'x' is not defined
>>> 
===================== RESTART: /home/user/RTR105/1B2.py =====================

===================== RESTART: /home/user/RTR105/1B2.py =====================
